targets:
  $default:
    builders:
      mockito:
        generate_for:
          - test/packed_ingredient_test.dart
          - test/ingredient_test.dart
          - test/meal_test.dart
        options:
          auto_mocks: true