// Mocks generated by Mockito 5.4.4 from annotations
// in foodplanner/test/page_tests/settings_test_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i9;

import 'package:foodplanner/auth/auth_provider.dart' as _i7;
import 'package:foodplanner/models/user.dart' as _i2;
import 'package:foodplanner/models/user_roles.dart' as _i8;
import 'package:foodplanner/services/user_service.dart' as _i4;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i4.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  _i6.Future<_i2.User> fetchUser(int? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchUser,
          [id],
        ),
        returnValue: _i6.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #fetchUser,
            [id],
          ),
        )),
      ) as _i6.Future<_i2.User>);

  @override
  _i6.Future<_i2.User> fetchLoggedInUser() => (super.noSuchMethod(
        Invocation.method(
          #fetchLoggedInUser,
          [],
        ),
        returnValue: _i6.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #fetchLoggedInUser,
            [],
          ),
        )),
      ) as _i6.Future<_i2.User>);

  @override
  _i6.Future<List<_i2.User>> fetchApproveUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchApproveUsers,
          [],
        ),
        returnValue: _i6.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i6.Future<List<_i2.User>>);

  @override
  _i6.Future<bool> updateApproveUsers(int? id) => (super.noSuchMethod(
        Invocation.method(
          #updateApproveUsers,
          [id],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i3.Response> createUser(
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            firstName,
            lastName,
            email,
            password,
            role,
          ],
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #createUser,
            [
              firstName,
              lastName,
              email,
              password,
              role,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> createUserPupil(
    String? firstName,
    String? lastName,
    String? email,
    String? password,
    List<int>? parentIds,
    int? classId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserPupil,
          [
            firstName,
            lastName,
            email,
            password,
            parentIds,
            classId,
          ],
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #createUserPupil,
            [
              firstName,
              lastName,
              email,
              password,
              parentIds,
              classId,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> loginUser(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #loginUser,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<List<_i2.User>> fetchAllGuardians() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllGuardians,
          [],
        ),
        returnValue: _i6.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i6.Future<List<_i2.User>>);

  @override
  _i6.Future<List<_i2.User>> fetchAllUsers() => (super.noSuchMethod(
        Invocation.method(
          #fetchAllUsers,
          [],
        ),
        returnValue: _i6.Future<List<_i2.User>>.value(<_i2.User>[]),
      ) as _i6.Future<List<_i2.User>>);

  @override
  _i6.Future<dynamic> updateArchived(int? id) => (super.noSuchMethod(
        Invocation.method(
          #updateArchived,
          [id],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> userInfo(int? id) => (super.noSuchMethod(
        Invocation.method(
          #userInfo,
          [id],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> updatePincode(String? updatedPincode) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePincode,
          [updatedPincode],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<dynamic> updatePassword(String? updatedPassword) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [updatedPassword],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<_i3.Response> updateUser(
    int? id,
    String? firstName,
    String? lastName,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [
            id,
            firstName,
            lastName,
            email,
          ],
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #updateUser,
            [
              id,
              firstName,
              lastName,
              email,
            ],
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<dynamic> deleteLoggedInUser() => (super.noSuchMethod(
        Invocation.method(
          #deleteLoggedInUser,
          [],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);

  @override
  _i6.Future<List<_i2.GuardianUser>> fetchAllGuardiansByPupilUserId(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllGuardiansByPupilUserId,
          [id],
        ),
        returnValue:
            _i6.Future<List<_i2.GuardianUser>>.value(<_i2.GuardianUser>[]),
      ) as _i6.Future<List<_i2.GuardianUser>>);

  @override
  _i6.Future<dynamic> deleteUser(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [id],
        ),
        returnValue: _i6.Future<dynamic>.value(),
      ) as _i6.Future<dynamic>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i7.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> login(
    _i8.UserRoles? role,
    String? token,
    bool? isApproved,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            role,
            token,
            isApproved,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> hasOneOfRoles(List<_i8.Role>? roles) => (super.noSuchMethod(
        Invocation.method(
          #hasOneOfRoles,
          [roles],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasRole(_i8.Role? role) => (super.noSuchMethod(
        Invocation.method(
          #hasRole,
          [role],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasAllRoles(Iterable<_i8.Role>? roles) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAllRoles,
          [roles],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> hasOneOfRolesUnapproved(List<_i8.Role>? roles) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasOneOfRolesUnapproved,
          [roles],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setRole(_i8.UserRoles? role) => (super.noSuchMethod(
        Invocation.method(
          #setRole,
          [role],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadFromStorage() => (super.noSuchMethod(
        Invocation.method(
          #loadFromStorage,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> retrieveToken() => (super.noSuchMethod(
        Invocation.method(
          #retrieveToken,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<_i8.UserRoles?> retrieveRole() => (super.noSuchMethod(
        Invocation.method(
          #retrieveRole,
          [],
        ),
        returnValue: _i6.Future<_i8.UserRoles?>.value(),
      ) as _i6.Future<_i8.UserRoles?>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
