name: Flutter Tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        
    - name: Go to the correct folder
      run: cd foodplanner

    - name: Get dependencies
      run: flutter pub get
      
    - name: Verify Flutter installation
      run: flutter doctor -v
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test test/service_tests --coverage --reporter expanded